# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/guillaume/dev/c++/Minecraft

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/guillaume/dev/c++/Minecraft

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/guillaume/dev/c++/Minecraft/CMakeFiles /home/guillaume/dev/c++/Minecraft/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/guillaume/dev/c++/Minecraft/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Minecraft

# Build rule for target.
Minecraft: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Minecraft
.PHONY : Minecraft

# fast build rule for target.
Minecraft/fast:
	$(MAKE) -f CMakeFiles/Minecraft.dir/build.make CMakeFiles/Minecraft.dir/build
.PHONY : Minecraft/fast

src/Core.o: src/Core.cpp.o

.PHONY : src/Core.o

# target to build an object file
src/Core.cpp.o:
	$(MAKE) -f CMakeFiles/Minecraft.dir/build.make CMakeFiles/Minecraft.dir/src/Core.cpp.o
.PHONY : src/Core.cpp.o

src/Core.i: src/Core.cpp.i

.PHONY : src/Core.i

# target to preprocess a source file
src/Core.cpp.i:
	$(MAKE) -f CMakeFiles/Minecraft.dir/build.make CMakeFiles/Minecraft.dir/src/Core.cpp.i
.PHONY : src/Core.cpp.i

src/Core.s: src/Core.cpp.s

.PHONY : src/Core.s

# target to generate assembly for a file
src/Core.cpp.s:
	$(MAKE) -f CMakeFiles/Minecraft.dir/build.make CMakeFiles/Minecraft.dir/src/Core.cpp.s
.PHONY : src/Core.cpp.s

src/Cube.o: src/Cube.cpp.o

.PHONY : src/Cube.o

# target to build an object file
src/Cube.cpp.o:
	$(MAKE) -f CMakeFiles/Minecraft.dir/build.make CMakeFiles/Minecraft.dir/src/Cube.cpp.o
.PHONY : src/Cube.cpp.o

src/Cube.i: src/Cube.cpp.i

.PHONY : src/Cube.i

# target to preprocess a source file
src/Cube.cpp.i:
	$(MAKE) -f CMakeFiles/Minecraft.dir/build.make CMakeFiles/Minecraft.dir/src/Cube.cpp.i
.PHONY : src/Cube.cpp.i

src/Cube.s: src/Cube.cpp.s

.PHONY : src/Cube.s

# target to generate assembly for a file
src/Cube.cpp.s:
	$(MAKE) -f CMakeFiles/Minecraft.dir/build.make CMakeFiles/Minecraft.dir/src/Cube.cpp.s
.PHONY : src/Cube.cpp.s

src/Keyboard.o: src/Keyboard.cpp.o

.PHONY : src/Keyboard.o

# target to build an object file
src/Keyboard.cpp.o:
	$(MAKE) -f CMakeFiles/Minecraft.dir/build.make CMakeFiles/Minecraft.dir/src/Keyboard.cpp.o
.PHONY : src/Keyboard.cpp.o

src/Keyboard.i: src/Keyboard.cpp.i

.PHONY : src/Keyboard.i

# target to preprocess a source file
src/Keyboard.cpp.i:
	$(MAKE) -f CMakeFiles/Minecraft.dir/build.make CMakeFiles/Minecraft.dir/src/Keyboard.cpp.i
.PHONY : src/Keyboard.cpp.i

src/Keyboard.s: src/Keyboard.cpp.s

.PHONY : src/Keyboard.s

# target to generate assembly for a file
src/Keyboard.cpp.s:
	$(MAKE) -f CMakeFiles/Minecraft.dir/build.make CMakeFiles/Minecraft.dir/src/Keyboard.cpp.s
.PHONY : src/Keyboard.cpp.s

src/Map.o: src/Map.cpp.o

.PHONY : src/Map.o

# target to build an object file
src/Map.cpp.o:
	$(MAKE) -f CMakeFiles/Minecraft.dir/build.make CMakeFiles/Minecraft.dir/src/Map.cpp.o
.PHONY : src/Map.cpp.o

src/Map.i: src/Map.cpp.i

.PHONY : src/Map.i

# target to preprocess a source file
src/Map.cpp.i:
	$(MAKE) -f CMakeFiles/Minecraft.dir/build.make CMakeFiles/Minecraft.dir/src/Map.cpp.i
.PHONY : src/Map.cpp.i

src/Map.s: src/Map.cpp.s

.PHONY : src/Map.s

# target to generate assembly for a file
src/Map.cpp.s:
	$(MAKE) -f CMakeFiles/Minecraft.dir/build.make CMakeFiles/Minecraft.dir/src/Map.cpp.s
.PHONY : src/Map.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/Minecraft.dir/build.make CMakeFiles/Minecraft.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/Minecraft.dir/build.make CMakeFiles/Minecraft.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/Minecraft.dir/build.make CMakeFiles/Minecraft.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... Minecraft"
	@echo "... edit_cache"
	@echo "... src/Core.o"
	@echo "... src/Core.i"
	@echo "... src/Core.s"
	@echo "... src/Cube.o"
	@echo "... src/Cube.i"
	@echo "... src/Cube.s"
	@echo "... src/Keyboard.o"
	@echo "... src/Keyboard.i"
	@echo "... src/Keyboard.s"
	@echo "... src/Map.o"
	@echo "... src/Map.i"
	@echo "... src/Map.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

